v1/models/chat.py
from uuid import uuid4
from datetime import datetime
from v1 import db

class Chat(db.Model):
    __tablename__ = 'chat'
    id = db.Column(db.Integer(), primary_key=True, autoincrement=True)
    message_id = db.Column(db.String(64), unique=True, default=str(uuid4()))
    sender_id = db.Column(db.String(), db.ForeignKey('user.user_id'))
    receiver_id = db.Column(db.String())
    message = db.Column(db.Text)
    filename = db.Column(db.String(64))
    time = db.Column(db.DateTime(), default=datetime.now())

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

v1/models/contact.py
from datetime import datetime
from v1 import db

class Contact(db.Model):
    __tablename__ = 'contact'
    id = db.Column(db.Integer(), primary_key=True, autoincrement=True)
    user_id = db.Column(db.String(), db.ForeignKey('user.user_id'))
    contact_id = db.Column(db.String(), db.ForeignKey('user.user_id'))
    contact_name = db.Column(db.String(60))
    created_at = db.Column(db.DateTime(), default=datetime.now())

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

v1/models/group.py
from uuid import uuid4
from datetime import datetime
from v1 import db

class Group(db.Model):
    __tablename__ = 'group'
    id = db.Column(db.Integer(), primary_key=True, autoincrement=True)
    group_id = db.Column(db.String(64), unique=True, default=str(uuid4()))
    group_name = db.Column(db.String(60))
    description = db.Column(db.String(255))
    profile = db.Column(db.String(64), default='default.png')
    created_at = db.Column(db.DateTime(), default=datetime.now())
    invite_link = db.Column(db.String(255))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

class UserGroup(db.Model):
    __tablename__ = 'usergroup'
    user_id = db.Column(db.String(), db.ForeignKey('user.user_id'), primary_key=True)
    group_id = db.Column(db.String(), db.ForeignKey('group.group_id'), primary_key=True)
    is_admin = db.Column(db.Boolean, default=False)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

v1/routes/chat/views.py
import os
from flask import Blueprint, render_template, flash, request, jsonify, current_app
from sqlalchemy import or_
from datetime import datetime, timedelta
from flask_login import current_user, login_required

from v1 import db
from v1.utils.helpers import update_account, save_picture
from v1.models.user import User
from v1.models.chat import Chat
from v1.models.db.user import query_contact_users

chat_view = Blueprint('chat_view', __name__, url_prefix='/')

@chat_view.route("users", methods=['GET', 'POST'])
@login_required
def user():

    if request.method == 'POST' and 'username' in request.form:
        
        form = request.form

        username = User.get_username(username=form['username'])

        if username:
            flash("Username is taken. Please choose a different username", "error")
    
        email = User.get_email(email=form['email'])

        if email:
            flash("Email already exists", "error")
        
        success, err = update_account(form)

        if success:
            flash('Account updated!', 'success')
        else:
            flash(f'Error updating account: {err}', 'error')
    
    return render_template('_partials/user_list.html', title='Users', current_user=current_user)
    

@chat_view.route("test", methods=['GET'])
def test():
    return render_template('test.html', title='Test')

@chat_view.route("get_users", methods=['GET'])
def get_contact_users():
    user_id = current_user.user_id
    q = request.args.get('query', '').strip()

    users = query_contact_users(user_id, q)

    users_data = []
    if users:
        # Fetch the latest chat for each user
        for user in users:
            latest_chat = (
                Chat.query.filter(
                    or_(
                        ((Chat.sender_id == user.user_id) & (Chat.receiver_id == current_user.user_id)),
                        ((Chat.sender_id == current_user.user_id) & (Chat.receiver_id == user.user_id))
                    )
                )
                .order_by(Chat.id.desc())
                .first()
            )

            user_data = {
                'user_id': user.user_id,
                'name': user.username,
                'profile': user.profile
            }

            if latest_chat and latest_chat.message:
                message = latest_chat.message
                if latest_chat.sender_id == current_user.user_id:
                    if len(message) < 60:
                        message = 'You: ' + latest_chat.message.replace('\n', ' ')
                    else:
                        message = 'You: ' + latest_chat.message[:60] + '...'.replace('\n', ' ')
                else:
                    if len(message) < 65:
                        message = latest_chat.message.replace('\n', ' ')
                    else:
                        message = latest_chat.message[:65] + '...'.replace('\n', ' ')
                time = latest_chat.time.strftime('%H:%M')

                user_data['latest_chat'] = {
                    'message': message,
                    'time': time
                }

            users_data.append(user_data)


    return jsonify({'users': users_data})

@chat_view.route("chat", methods=['GET', 'POST'])
@login_required
def chat():
    user = None

    # Get incoming user
    user_id = request.args.get('user_id')
    status = None
    if user_id:
        current_time = datetime.now()
        user = User.query.filter_by(user_id=user_id).first()
        status = user.status
        if status.strftime('%Y-%m-%d %H:%M') == current_time.strftime('%Y-%m-%d %H:%M'):
            status = 'Online'
        elif status.date() == current_time.date():
            status = f'Today {status.strftime("%H:%M")}'
        elif status.date() == current_time.date() - timedelta(days=1):
            status = f'Yesterday {status.strftime("%H:%M")}'
        elif current_time - timedelta(days=7) <= status:
            status = f'{status.strftime("%A")} {status.strftime("%H:%M")}'
        else:
            status = status.strftime('%Y-%m-%d')

    messages = ( 
        Chat.query.filter(
            (
                (Chat.sender_id == current_user.user_id) & (Chat.receiver_id == user_id)
            )
            | (
                (Chat.sender_id == user_id) & (Chat.receiver_id == current_user.user_id)
            )
        ).order_by(Chat.id).all()    
    )

    if request.method == 'POST' and 'username' in request.form:
        form = request.form

        username = User.get_username(username=form['username'])

        if username:
            flash("Username is taken. Please choose a different username", "error")
    
        email = User.get_email(email=form['email'])

        if email:
            flash("Email already exists", "error")
        
        success, err = update_account(form)

        if success:
            flash('Account updated!', 'success')
        else:
            flash(f'Error updating account: {err}', 'error')

    
    return render_template('chat.html', title='Chat', target_user=user, messages=messages, status=status)


@chat_view.route("get_user_messages", methods=['GET'])
def get_messages():
    if current_user: 
        user_id = request.args.get('user_id')
        if user_id:
            messages = ( 
                    Chat.query.filter(
                        (
                            (Chat.sender_id == current_user.user_id) & (Chat.receiver_id == user_id)
                        )
                        | (
                            (Chat.sender_id == user_id) & (Chat.receiver_id == current_user.user_id)
                        )
                    ).order_by(Chat.id).all()    
                )

            message_list = []

            for message in messages:

                message_data = {
                    'sender_id': message.sender_id,
                    'receiver_id': message.receiver_id,
                    'time': message.time.strftime('%Y-%m-%d_%H:%M'),
                }

                if message.message:
                    message_data['message'] = message.message

                if message.filename:
                    message_data['file'] = message.filename

                message_list.append(message_data)

        else:
            return jsonify({'error': 'user_id not provided'}), 400
        
    else:
        return jsonify({'error': 'unauthorized'}), 401

    return jsonify({'messages': message_list})

@chat_view.route("upload_profile", methods=['POST'])
def upload_image():
    file = request.files.get('file')
    old_picture_filename = current_user.profile
    if file:
        picture_file = save_picture(file, old_picture_filename)
        current_user.profile = picture_file
        db.session.commit()
        return jsonify({'success': True, 'message': 'File uploaded successfully'})
    else:
        if old_picture_filename != 'default.png':
            old_picture_path = os.path.join(current_app.root_path, 'static/images/profile', old_picture_filename)
            if os.path.exists(old_picture_path):
                os.remove(old_picture_path)
        current_user.profile = 'default.png'
        db.session.commit()
        return jsonify({'success': True, 'message': 'Profile picture unlinked successfully'})

v1/routes/group/views.py
from flask import Blueprint, redirect, render_template, flash, request, jsonify, url_for
from sqlalchemy import or_
from flask_login import current_user, login_required
from uuid import uuid4

from v1.models.user import User
from v1.models.chat import Chat
from v1.models.group import Group, UserGroup
from v1.models.db.group import get_groups_for_user
from v1.utils.helpers import update_account
from v1.utils.random import Generate


group_view = Blueprint('group_view', __name__, url_prefix='/')

@group_view.route("groups", methods=['GET', 'POST'])
@login_required
def groups(): 

    if request.method == 'POST' and 'groupname' in request.form:
        
        group_id = str(uuid4())
        groupname = request.form['groupname']
        description = request.form['description']
        inviteid = Generate.random_string(length=64)
        group = Group(group_id=group_id, group_name=groupname, description=description, invite_link=inviteid)
        group.save()

        join_group = UserGroup(user_id=current_user.user_id, group_id=group_id, is_admin=True)
        join_group.save()

        flash(f'{groupname} group created!', 'success')  

    if request.method == 'POST' and 'username' in request.form:

        form = request.form

        username = User.get_username(username=form['username'])

        if username:
            flash("Username is taken. Please choose a different username", "error")
    
        email = User.get_email(email=form['email'])

        if email:
            flash("Email already exists", "error")
        
        success, err = update_account(form)

        if success:
            flash('Account updated!', 'success')
        else:
            flash(f'Error updating account: {err}', 'error')

    return render_template('_partials/group_list.html', title='Groups')


@group_view.route("get_groups", methods=['GET'])
def get_groups():
    user_id = current_user.user_id
    q = request.args.get('query', '').strip()
    if not q:
        q = None
    groups = get_groups_for_user(user_id, query=q)

    groups_data = []
    if groups:
        # Fetch the latest chat for each user
        for group in groups:

            members = UserGroup.query.filter_by(group_id = group.group_id).all()

            for member in members:                
                latest_chat = (
                    Chat.query.filter(
                        or_(
                            ((Chat.sender_id == user_id) & (Chat.receiver_id == group.group_id)),
                            ((Chat.sender_id == member.user_id) & (Chat.receiver_id == group.group_id))
                        )
                    )
                    .order_by(Chat.id.desc())
                    .first()
                )

                group_data = {
                    'group_id': group.group_id,
                    'name': group.group_name,
                    'profile': group.profile
                }

                if latest_chat and latest_chat.message:
                    message = latest_chat.message
                    if latest_chat.sender_id == current_user.user_id:
                        if len(message) < 60:
                            message = 'You: ' + latest_chat.message.replace('\n', ' ')
                        else:
                            message = 'You: ' + latest_chat.message[:60] + '...'.replace('\n', ' ')
                    else:
                        if len(message) < 65:
                            message = latest_chat.message.replace('\n', ' ')
                        else:
                            message = latest_chat.message[:65] + '...'.replace('\n', ' ')
                    time = latest_chat.time.strftime('%H:%M')

                    group_data['latest_chat'] = {
                        'message': message,
                        'time': time
                    }

                groups_data.append(group_data)

    return jsonify({'groups': groups_data})

@group_view.route("group", methods=['GET', 'POST'])
@login_required
def group():

    group = None
    members = None
    messages = None

    # Get group id
    group_id = request.args.get('group_id')

    if group_id:

        groupuser = UserGroup.query.filter((UserGroup.group_id==group_id) & (UserGroup.user_id == current_user.user_id)).first()

        if not groupuser:
            return redirect(url_for('group_view.group'))

        group = Group.query.filter_by(group_id=group_id).first()

        user_group = UserGroup.query.filter_by(group_id=group_id).all()

        for user in user_group:
            members = User.query.filter_by(user_id=user.user_id).all()

        messages = Chat.query.filter(Chat.receiver_id==group_id).order_by(Chat.id).all() 

    if request.method == 'POST' and 'username' in request.form:
        form = request.form

        username = User.get_username(username=form['username'])

        if username:
            flash("Username is taken. Please choose a different username", "error")
    
        email = User.get_email(email=form['email'])

        if email:
            flash("Email already exists", "error")
        
        success, err = update_account(form)
        
        if success:
            flash('Account updated!', 'success')
        else:
            flash(f'Error updating account: {err}', 'error')

    
    return render_template('group.html', title='Group', group=group, members=members, messages=messages)


@group_view.route("get_group_messages", methods=['GET'])
def get_messages():
    if current_user: 
        group_id = request.args.get('group_id')

        if group_id:
            message_list = []

            messages = Chat.query.filter(Chat.receiver_id == group_id).order_by(Chat.id).all() 

            for message in messages:
                
                user = User.query.filter_by(user_id=message.sender_id).first()

                message_data = {
                    'receiver_id': message.receiver_id,
                    'time': message.time.strftime('%Y-%m-%d_%H:%M'),
                    'sender': {
                        'id': message.sender_id,
                        'username': user.username,
                        'profile': user.profile
                    }
                }

                if message.message:
                    message_data['message'] = message.message

                if message.filename:
                    message_data['file'] = message.filename

                message_list.append(message_data)
        else:
            return jsonify({'error': 'group_id not provided'}), 400
        
    else:
        return jsonify({'error': 'unauthorized'}), 401

    return jsonify({'messages': message_list})


@group_view.route("join-group/<string:id>", methods=['GET'])
@login_required
def join_group(id):

    if not id:
        return redirect(url_for('group_view.group'))
    
    invite_id = id
    
    group = Group.query.filter_by(invite_link=invite_id).first()

    if group:

        group_id = group.group_id
        group_url = url_for('group_view.group')

        groupuser = UserGroup.query.filter((UserGroup.group_id==group_id) & (UserGroup.user_id == current_user.user_id)).first()

        if groupuser:
            return redirect(group_url + f'?group_id={group_id}')
        
        join_group = UserGroup(user_id=current_user.user_id, group_id=group_id)
        join_group.save()

        return redirect(group_url + f'?group_id={group_id}')

    else:
        flash(f'Invalid invite id!', 'error')
        
        return redirect(url_for('group_view.group'))

v1/templates/auth-layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#047857">

    <link rel="icon" href="{{ url_for('static', filename='images/icons/logo.svg') }}" type="image/x-icon" />
    <link rel="icon" href="{{ url_for('static', filename='images/icons/logo_192x192.png') }}" />
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='images/icons/logo.svg') }}" />
    <link rel="manifest" href="{{ url_for('static', filename='pwa/manifest.json') }}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if title %}
    <title>{{ title }} - HiChat</title>
    {% else %}
        <title>HiChat</title>
    {% endif %}
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <!-- <script type="text/javascript">
                const Toast = Swal.mixin({
                    toast: true,
                    position: "top-end",
                    showConfirmButton: false,
                    timer: 3000,
                    timerProgressBar: true,
                    didOpen: (toast) => {
                        toast.onmouseenter = Swal.stopTimer;
                        toast.onmouseleave = Swal.resumeTimer;
                    }
                });
                Toast.fire({
                    icon: "{{ category }}",
                    title: "{{ message }}"
                });
            </script> -->
        {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock content %}
    <script type="text/javascript">
        function swalToast(category, message) {
            const Toast = Swal.mixin({
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
            });
            Toast.fire({
                icon: category,
                title: message
            });
        }
    </script>
    {% block script %}{% endblock script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

v1/templates/chat.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/chat.css') }}">
<script>
    var currentname = "{{current_user.username}}";
    var targetname = null;
</script>
{% endblock style %}
{% block content %}
    <!-- start: Chat -->
    <section class="chat-section">
        <div class="chat-container">
            {% include '_partials/sidebar.html' %}
            <!-- start: Content -->
            <div class="chat-content">
                <!-- start: Content side -->
                <div class="content-sidebar">
                    <div class="content-sidebar-title">Chats</div>
                    <form class="content-sidebar-form" style="display: none;">
                        <input type="search" class="content-sidebar-input" placeholder="Search..." id="searchInput">
                        <button type="button" class="content-sidebar-submit" id="searchButton"><i class="ri-search-line"></i></button>
                    </form>
                    <div class="content-messages">
                        <ul class="content-messages-list" id="users-container">
                            <!-- <li class="content-message-title"><span>Recent</span></li>                       -->
                        </ul>
                    </div>
                </div>
                <!-- end: Content side -->
                <!-- start: Conversation -->
                
                {% if target_user %}
                <script>targetname = "{{target_user.username}}";</script>                
                <div class="conversation">
                    <div class="conversation-top">
                        <a href="{{ url_for('chat_view.user') }}"><button type="button" class="conversation-back"><i class="ri-arrow-left-line"></i></button></a>
                        <div class="conversation-user">
                            <img class="conversation-user-image" src="{{ url_for('static', filename='images/profile/' + target_user.profile) }}" alt="">
                            <div>
                                <div class="conversation-user-name">{{ target_user.username }}</div>
                                <div class="conversation-user-status online">{{status}}</div>
                            </div>
                        </div>
                        <div class="conversation-buttons">
                            <button type="button" id="voice-call"><i class="ri-phone-fill"></i></button>
                            <!-- <button type="button" id="video-call"><i class="ri-vidicon-line"></i></button> -->
                            <button type="button"><i class="ri-information-line"></i></button>
                        </div>
                    </div>
                    <div class="conversation-main">
                        <ul class="conversation-wrapper" id="messages-container"></ul>                        
                    </div>
                    <form method="post" class="conversation-form" id="chatForm">
                        <button type="button" class="conversation-form-button emoji-picker"><i class="ri-emotion-line"></i></button>
                        <div class="conversation-attachment">
                            <button type="button" class="conversation-form-button conversation-attachment-toggle"><i class="ri-attachment-2"></i></button>
                            <ul class="conversation-attachment-dropdown">
                                <input type="file" name="file" hidden>
                                <!-- <li><i class="ri-image-line"></i>Attach image</li> -->
                                <li><i class="ri-file-2-line"></i></i>Attach file</li>
                            </ul>
                        </div>
                        <div class="conversation-form-group">
                            <textarea class="conversation-form-input" id="msg" name="msg" rows="1" placeholder="Type here..." required></textarea>
                            <button type="button" class="conversation-form-record"><i class="ri-mic-line"></i></button>
                            <button type="button" class="conversation-form-submit" onclick="submitForm()"><i class="ri-send-plane-2-line"></i></button>
                        </div>
                    </form>
                </div>
                {% else %}
                <div class="conversation conversation-default">
                    <i class="ri-chat-3-line"></i>
                    <h3>HiChat Chat App</h3>
                    <p>Select chat to view conversation or start chatting!</p>  
                    <p>Your chats appear on this window.</p>           
                </div>
                <div class="conversation conversation-default sm">
                    <i class="ri-chat-3-line"></i>
                    <h3>HiChat Chat App</h3>
                    <p>User ID not provided or no user selected!</p>  
                    <p>Your chats appear on this window.</p> 
                </div>
                {% endif %}
                <!-- end: Conversation -->
            </div>
            <!-- end: Content -->
        </div>
    </section>
{% endblock content %}

{% block script %}
<script src="{{ url_for('static', filename='js/chat/users.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/chat/chat.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/emoji/emojiPicker.js') }}"></script>
{% endblock script %}

v1/templates/contact.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/chat.css') }}">
{% endblock style %}
{% block content %}
    <!-- start: Chat -->
    <section class="chat-section">
        <div class="chat-container">
            {% include '_partials/sidebar.html' %}
            <!-- start: Content -->
            <div class="chat-content">
                <!-- start: Content side -->
                <div class="content-sidebar">
                    <div class="content-sidebar-title">Chats</div>
                    <form class="content-sidebar-form" style="display: none;">
                        <input type="search" class="content-sidebar-input" placeholder="Search..." id="searchInput">
                        <button type="button" class="content-sidebar-submit" id="searchButton"><i class="ri-search-line"></i></button>
                    </form>
                    <div class="content-messages">
                        <ul class="content-messages-list" id="contacts-container">
                            <!-- <li class="content-message-title"><span>Recent</span></li>                       -->
                        </ul>
                    </div>
                </div>
                <!-- end: Content side -->
                <!-- start: Conversation -->
                
                {% if contact %}            
                <div class="conversation">
                    <div class="conversation-top">
                        <a href="{{ url_for('chat_view.user') }}"><button type="button" class="conversation-back"><i class="ri-arrow-left-line"></i></button></a>
                        <div class="conversation-user">
                            <img class="conversation-user-image" src="{{ url_for('static', filename='images/profile/' + contact.profile) }}" alt="">
                            <div>
                                <div class="conversation-user-name">{{ contact.username }}</div>
                                <div class="conversation-user-status online">{{status}}</div>
                            </div>
                        </div>
                        <div class="conversation-buttons">
                            <button type="button" id="voice-call"><i class="ri-phone-fill"></i></button>
                            <!-- <button type="button" id="video-call"><i class="ri-vidicon-line"></i></button> -->
                            <button type="button"><i class="ri-information-line"></i></button>
                        </div>
                    </div>
                    <div class="conversation-main">
                        <ul class="conversation-wrapper" id="messages-container"></ul>                        
                    </div>
                    <form method="post" class="conversation-form" id="chatForm">
                        <button type="button" class="conversation-form-button emoji-picker"><i class="ri-emotion-line"></i></button>
                        <div class="conversation-attachment">
                            <button type="button" class="conversation-form-button conversation-attachment-toggle"><i class="ri-attachment-2"></i></button>
                            <ul class="conversation-attachment-dropdown">
                                <input type="file" name="file" hidden>
                                <!-- <li><i class="ri-image-line"></i>Attach image</li> -->
                                <li><i class="ri-file-2-line"></i></i>Attach file</li>
                            </ul>
                        </div>
                        <div class="conversation-form-group">
                            <textarea class="conversation-form-input" id="msg" name="msg" rows="1" placeholder="Type here..." required></textarea>
                            <button type="button" class="conversation-form-record"><i class="ri-mic-line"></i></button>
                            <button type="button" class="conversation-form-submit" onclick="submitForm()"><i class="ri-send-plane-2-line"></i></button>
                        </div>
                    </form>
                </div>
                {% else %}
                <div class="conversation conversation-default">
                    <i class="ri-chat-3-line"></i>
                    <h3>HiChat Chat App</h3>
                    <p>Select contact to view details!</p>  
                    <p>Your contact information appear here.</p>           
                </div>
                <div class="conversation conversation-default sm">
                    <i class="ri-chat-3-line"></i>
                    <h3>HiChat Chat App</h3>
                    <p>No contact selected!</p>  
                    <p>Your contact information appear here.</p> 
                </div>
                {% endif %}
                <!-- end: Conversation -->
            </div>
            <!-- end: Content -->
        </div>
    </section>
{% endblock content %}

{% block script %}
<script src="{{ url_for('static', filename='js/contact/contact_list.js') }}"></script>
<script src="{{ url_for('static', filename='js/contact/contact.js') }}"></script>
{% endblock script %}

v1/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script src="{{ url_for('static', filename='js/users/users.js') }}"></script>
    <script src="{{ url_for('static', filename='js/users/chat.js') }}"></script>
</body>
</html>

v1/templates/verify-email.html
{% extends 'auth-layout.html' %}
{% block content %}
<script type="text/javascript">
    Swal.fire({
        title: "{{ _title }}",
        text: "{{ text }}",
        icon: "{{ icon }}",
        showConfirmButton: false
    });

    setTimeout(function(){
        window.location.href = "{{ url_for('auth_view.login') }}";
    }, 5000);
</script>
{% endblock content %}